// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type V1UsersMock struct{}

func (m *V1UsersMock) Create(ctx context.Context, req *CreateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        80,
				FirstName: "mollitia",
				Lastname:  "ad",
				Email:     "CraigHowell@Voomm.org",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        859,
				FirstName: "odit",
				Lastname:  "ad",
				Email:     "RogerHenderson@Dynava.com",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        934,
				FirstName: "ea",
				Lastname:  "expedita",
				Email:     "AshleyMontgomery@Mymm.edu",
				Visible:   true,
			},
		}
	return res, nil
}
func (m *V1UsersMock) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	res :=
		&UserReply{
			User: &User{
				Id:        781,
				FirstName: "in",
				Lastname:  "ut",
				Email:     "HaroldHarrison@Fivechat.com",
				Visible:   false,
			},
		}
	return res, nil
}
