// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	User                 *CreateUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *CreateUser {
	if m != nil {
		return m.User
	}
	return nil
}

type FindByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByIdRequest) Reset()         { *m = FindByIdRequest{} }
func (m *FindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindByIdRequest) ProtoMessage()    {}
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *FindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIdRequest.Unmarshal(m, b)
}
func (m *FindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIdRequest.Merge(m, src)
}
func (m *FindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindByIdRequest.Size(m)
}
func (m *FindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIdRequest proto.InternalMessageInfo

func (m *FindByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByEmailRequest) Reset()         { *m = FindByEmailRequest{} }
func (m *FindByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*FindByEmailRequest) ProtoMessage()    {}
func (*FindByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *FindByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByEmailRequest.Unmarshal(m, b)
}
func (m *FindByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByEmailRequest.Marshal(b, m, deterministic)
}
func (m *FindByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByEmailRequest.Merge(m, src)
}
func (m *FindByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_FindByEmailRequest.Size(m)
}
func (m *FindByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByEmailRequest proto.InternalMessageInfo

func (m *FindByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	NewPassword          string   `protobuf:"bytes,4,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateUserRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type UserReply struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReply) Reset()         { *m = UserReply{} }
func (m *UserReply) String() string { return proto.CompactTextString(m) }
func (*UserReply) ProtoMessage()    {}
func (*UserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *UserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReply.Unmarshal(m, b)
}
func (m *UserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReply.Marshal(b, m, deterministic)
}
func (m *UserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReply.Merge(m, src)
}
func (m *UserReply) XXX_Size() int {
	return xxx_messageInfo_UserReply.Size(m)
}
func (m *UserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserReply proto.InternalMessageInfo

func (m *UserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "users.CreateUserRequest")
	proto.RegisterType((*FindByIdRequest)(nil), "users.FindByIdRequest")
	proto.RegisterType((*FindByEmailRequest)(nil), "users.FindByEmailRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "users.UpdateUserRequest")
	proto.RegisterType((*UserReply)(nil), "users.UserReply")
}

func init() {
	proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea)
}

var fileDescriptor_030765f334c86cea = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x4d, 0x9a, 0xc6, 0x66, 0x16, 0xd4, 0x0c, 0x22, 0x31, 0x08, 0xd6, 0x05, 0x41, 0x44,
	0x02, 0x56, 0xe8, 0x41, 0x3c, 0x55, 0x14, 0xbc, 0x88, 0x04, 0xea, 0xc1, 0x5b, 0x74, 0x57, 0x09,
	0xa4, 0x4d, 0xdc, 0x4d, 0x29, 0x39, 0xf9, 0xc8, 0xbe, 0x82, 0x64, 0x37, 0x49, 0xd3, 0xb4, 0x1e,
	0xe7, 0xff, 0x91, 0x99, 0xfc, 0x58, 0x20, 0x0b, 0xc9, 0x85, 0x0c, 0x32, 0x91, 0xe6, 0x29, 0xf6,
	0xd5, 0xe0, 0x93, 0xbc, 0xc8, 0x78, 0xa5, 0xd1, 0x5b, 0x70, 0xef, 0x05, 0x8f, 0x72, 0x3e, 0x95,
	0x5c, 0x84, 0xfc, 0x7b, 0xc1, 0x65, 0x8e, 0xe7, 0x60, 0x95, 0x51, 0xcf, 0x18, 0x1a, 0x17, 0x64,
	0xe4, 0x06, 0xba, 0xd0, 0xca, 0x29, 0x9b, 0x9e, 0xc1, 0xfe, 0x63, 0x3c, 0x67, 0x93, 0xe2, 0x89,
	0xd5, 0xcd, 0x3d, 0x30, 0x63, 0xa6, 0x7a, 0xbd, 0xd0, 0x8c, 0x19, 0xbd, 0x04, 0xd4, 0x91, 0x87,
	0x59, 0x14, 0x27, 0x75, 0xea, 0x10, 0xfa, 0xbc, 0x9c, 0x55, 0xd0, 0x09, 0xf5, 0x40, 0x7f, 0xc0,
	0x9d, 0x66, 0xac, 0x73, 0x4a, 0xe7, 0x83, 0x78, 0x02, 0xce, 0x67, 0x2c, 0x64, 0xfe, 0x1c, 0xcd,
	0xb8, 0x67, 0xaa, 0xfa, 0x4a, 0x40, 0x1f, 0x06, 0x49, 0x54, 0x99, 0x3d, 0x65, 0x36, 0x33, 0x0e,
	0x81, 0xcc, 0xf9, 0xf2, 0x25, 0x92, 0x72, 0x99, 0x0a, 0xe6, 0x59, 0xca, 0x6e, 0x4b, 0xf4, 0x0a,
	0x1c, 0xbd, 0x3a, 0x4b, 0x0a, 0x3c, 0x5d, 0x63, 0x40, 0x2a, 0x06, 0xab, 0xbf, 0x1f, 0xfd, 0x1a,
	0xb0, 0xfb, 0x7a, 0x5d, 0x0a, 0x12, 0xc7, 0x60, 0x6b, 0x3a, 0xe8, 0x05, 0x9a, 0xf8, 0x06, 0x54,
	0xff, 0xa0, 0x72, 0x9a, 0x15, 0x74, 0x07, 0xc7, 0x30, 0xa8, 0x09, 0xe2, 0x51, 0xe5, 0x77, 0x90,
	0x6e, 0xed, 0xdd, 0x01, 0x69, 0x61, 0xc5, 0xe3, 0xb5, 0x6a, 0x1b, 0xf5, 0x3f, 0x5b, 0x6d, 0x0d,
	0xba, 0xb9, 0x76, 0x83, 0xfb, 0xb6, 0xde, 0xc4, 0x7e, 0xb3, 0xbe, 0x44, 0xf6, 0xf1, 0x6e, 0xab,
	0xa7, 0x73, 0xf3, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x9b, 0x39, 0xa1, 0x5d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// V1UsersClient is the client API for V1Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type V1UsersClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserReply, error)
	FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*UserReply, error)
	FindByEmail(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserReply, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserReply, error)
}

type v1UsersClient struct {
	cc grpc.ClientConnInterface
}

func NewV1UsersClient(cc grpc.ClientConnInterface) V1UsersClient {
	return &v1UsersClient{cc}
}

func (c *v1UsersClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/users.V1Users/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1UsersClient) FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/users.V1Users/FindById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1UsersClient) FindByEmail(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/users.V1Users/FindByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1UsersClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/users.V1Users/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// V1UsersServer is the server API for V1Users service.
type V1UsersServer interface {
	Create(context.Context, *CreateUserRequest) (*UserReply, error)
	FindById(context.Context, *FindByIdRequest) (*UserReply, error)
	FindByEmail(context.Context, *FindByEmailRequest) (*UserReply, error)
	Update(context.Context, *UpdateUserRequest) (*UserReply, error)
}

// UnimplementedV1UsersServer can be embedded to have forward compatible implementations.
type UnimplementedV1UsersServer struct {
}

func (*UnimplementedV1UsersServer) Create(ctx context.Context, req *CreateUserRequest) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedV1UsersServer) FindById(ctx context.Context, req *FindByIdRequest) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (*UnimplementedV1UsersServer) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByEmail not implemented")
}
func (*UnimplementedV1UsersServer) Update(ctx context.Context, req *UpdateUserRequest) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterV1UsersServer(s *grpc.Server, srv V1UsersServer) {
	s.RegisterService(&_V1Users_serviceDesc, srv)
}

func _V1Users_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1UsersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.V1Users/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1UsersServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1Users_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1UsersServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.V1Users/FindById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1UsersServer).FindById(ctx, req.(*FindByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1Users_FindByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1UsersServer).FindByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.V1Users/FindByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1UsersServer).FindByEmail(ctx, req.(*FindByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1Users_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1UsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.V1Users/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1UsersServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _V1Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.V1Users",
	HandlerType: (*V1UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _V1Users_Create_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _V1Users_FindById_Handler,
		},
		{
			MethodName: "FindByEmail",
			Handler:    _V1Users_FindByEmail_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _V1Users_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
